# Generated by Django 3.0.7 on 2020-06-10 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('txt', models.TextField()),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
