# Generated by Django 3.0.7 on 2020-06-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mail_address',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
