# Generated by Django 3.0.7 on 2020-06-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mail_address',
            field=models.TextField(null=True),
        ),
    ]
