# Generated by Django 3.0.7 on 2020-06-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contact_mail_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.TextField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
