# Generated by Django 3.0.7 on 2020-06-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
