# Generated by Django 3.0.7 on 2020-06-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='info',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
