# Generated by Django 3.0.7 on 2020-06-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
