# Generated by Django 3.0.7 on 2020-06-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_posts_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='tag',
            new_name='tags',
        ),
    ]
