# Generated by Django 3.0.7 on 2020-06-21 08:41

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200621_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
