# Generated by Django 3.0.7 on 2020-06-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200613_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='txt',
            new_name='text',
        ),
    ]
