# Generated by Django 3.0.7 on 2020-06-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200610_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
