# Generated by Django 3.0.7 on 2020-06-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200612_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
