# Generated by Django 3.0.7 on 2020-06-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200613_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='Update_date',
            new_name='update_date',
        ),
    ]
